jwt:
  expires-time: 7d
  buffer-time: 1d
# auto config
autocode:
  root: "" # 根路径
zap:
  level: info # 打印日志级别，第一此级别不打印
  format: console
  prefix: "[github.com/Yukilwc/go_gin_server_frame]"
  director: log
  show-line: true
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  log-in-console: true
system:
  db-type: mysql
# mysql connect configuration
# 未初始化之前请勿手动修改数据库信息！！！如果一定要手动初始化请看（https://gin-vue-admin.com/docs/first_master）
mysql:
  path: "localhost"
  port: "3306"
  config: ""
  db-name: "ggg_test"
  username: "testuser"
  password: "123456"
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: ""
  log-zap: false

